In [1]:

import numpy as np
Sidelength=4
arr = np.arange(Sidelength**2)
arr=arr.reshape(Sidelength,Sidelength)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [1]:
sample = [('Jack', 76), ('Beneth', 78), ('Cirus', 77), ('Faiz', 79)]
sample.sort(key=lambda a: a[1])
print(sample)

[('Jack', 76), ('Cirus', 77), ('Beneth', 78), ('Faiz', 79)]


In [3]:
[i[0] for i in sample][0].rfind("x")

-1

In [5]:
sample[1:3]

[('Cirus', 77), ('Beneth', 78)]

In [61]:
rows = np.arange(Sidelength)
rowsshuffed=rows
colsshuffed=rows
np.random.shuffle(rowsshuffed)
np.random.shuffle(colsshuffed)
print(rowsshuffed)

[2 3 0 1]


In [64]:
arrcopy=arr.copy()
for i,r in enumerate(rowsshuffed):
    arr[i,:]=arrcopy[r,:]
arr

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [4]:
arrcols = arr.reshape(4,4).T.flatten()

array([ 0,  4,  8, 12,  1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15])

In [47]:
np.random.shuffle(arr)
arr

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [69]:
trans=np.diag([1,1,1,1])
trans.T*arr

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [80]:
def createstartvals(x1,x2,y1,y2,SideLength):#this essentially creates a flattened grid for using as input into pyopenclfuncs
    Xlength=int(abs((x1-x2)/(y1-y2)*SideLength))
    Ylength=int(abs((y1-y2)/(x1-x2)*SideLength))
    Xs=np.linspace(x1,x2,Xlength,dtype=np.complex128)
    Ys=np.linspace(y1*1j,y2*1j,Ylength)
    Vals=np.zeros(SideLength*SideLength,dtype=np.complex128)
    """for i,x in enumerate(Xs):
        for j,y in enumerate(Ys):
            Vals[i,j]=x+y"""
    for i in range(Ylength):
        Vals[i*Xlength:i*Xlength+Xlength]=Xs
        Vals[i*Xlength:i*Xlength+Xlength]+=Ys[i]#every y val repeated side length times"""
    return Vals.reshape(Ylength,Xlength)#can be reshaped into square grid    
createstartvals(-2,2,-4,4,8)

4
16


array([[-2.        -4.j        , -0.66666667-4.j        ,
         0.66666667-4.j        ,  2.        -4.j        ],
       [-2.        -3.46666667j, -0.66666667-3.46666667j,
         0.66666667-3.46666667j,  2.        -3.46666667j],
       [-2.        -2.93333333j, -0.66666667-2.93333333j,
         0.66666667-2.93333333j,  2.        -2.93333333j],
       [-2.        -2.4j       , -0.66666667-2.4j       ,
         0.66666667-2.4j       ,  2.        -2.4j       ],
       [-2.        -1.86666667j, -0.66666667-1.86666667j,
         0.66666667-1.86666667j,  2.        -1.86666667j],
       [-2.        -1.33333333j, -0.66666667-1.33333333j,
         0.66666667-1.33333333j,  2.        -1.33333333j],
       [-2.        -0.8j       , -0.66666667-0.8j       ,
         0.66666667-0.8j       ,  2.        -0.8j       ],
       [-2.        -0.26666667j, -0.66666667-0.26666667j,
         0.66666667-0.26666667j,  2.        -0.26666667j],
       [-2.        +0.26666667j, -0.66666667+0.26666667j,
      

In [1]:
#With floyds tortoise and hair
StabilityFractalWithCycle="""
    int Counter = 0;
    dtype_t Const = X[i];//dont rename
    
    dtype_t pastval = (dtype_t){0,0};
    dtype_t Xi=(dtype_t){0,0};
    
    while (dtype_abs_squared(Xi)<DivLim && Counter<N){
        
        Xi=__f(Xi,Const)__;
        Xi=__f(Xi,Const)__;
        
        pastval=__f(pastval,Const)__;
        Counter+=1;
        if (fabs(Xi.real-pastval.real)< cycleacc && fabs(Xi.imag-pastval.imag)< cycleacc){
                
            Xi.real=-Counter;//negative so it can be seen easily where cycles have been found
            Counter=N+1;
            PYOPENCL_ELWISE_CONTINUE;//pretty sure this does nothing
            
        }
        
    }

0